export const META = {
  name: "atlas-api-public",
  description:
    "Versioned public API for the estate: registry, RAG search, stats, infra health, and the status badge",
  version: "1.1.0",
  endpoints: [
    { method: "GET", path: "/v1", description: "Endpoint index" },
    { method: "GET", path: "/v1/docs", description: "Human documentation" },
    { method: "GET", path: "/v1/openapi.json", description: "OpenAPI 3.0 spec" },
    { method: "GET", path: "/v1/registry", description: "Worker registry, stable public shape" },
    { method: "GET", path: "/v1/search", description: "RAG search over the estate corpus (?q=)" },
    { method: "GET", path: "/v1/stats", description: "Estate stats: repos, components, measured uptime" },
    { method: "GET", path: "/v1/slo", description: "Per-day probe counters for error budget maths; window labelled" },
    { method: "GET", path: "/v1/infra/status", description: "Infra health state from specular-sentinel" },
    { method: "GET", path: "/v1/rag/stats", description: "RAG query counts, no query text" },
    { method: "GET", path: "/v1/badge/status", description: "SVG status badge" },
    { method: "GET", path: "/v1/control-plane/summary", description: "Bounded public control-plane summary" },
    { method: "GET", path: "/v1/control-plane/tools/openapi.json", description: "Authenticated nine-operation Ramone tool spec" },
    { method: "GET", path: "/v1/control-plane/tools/summary", description: "Authenticated estate summary tool" },
    { method: "GET", path: "/v1/control-plane/tools/services/{service_id}", description: "Authenticated service status tool" },
    { method: "GET", path: "/v1/control-plane/tools/releases", description: "Authenticated release status tool" },
    { method: "GET", path: "/v1/control-plane/tools/findings", description: "Authenticated active findings tool" },
    { method: "GET", path: "/v1/control-plane/tools/quota", description: "Authenticated quota projection tool" },
    { method: "GET", path: "/v1/control-plane/tools/backups", description: "Authenticated backup status tool" },
    { method: "GET", path: "/v1/control-plane/tools/gardener/proposals", description: "Authenticated Gardener proposal tool" },
    { method: "GET", path: "/v1/control-plane/tools/runbooks/search", description: "Authenticated runbook search tool" },
    { method: "GET", path: "/v1/control-plane/tools/evidence/search", description: "Authenticated evidence metadata search tool" },
    { method: "POST", path: "/v1/infra/report", description: "Sentinel ingest (bearer)" },
    { method: "POST", path: "/v1/rag/report", description: "Corpus summary ingest (bearer)" },
  ],
  source: "https://github.com/AtlasReaper311/atlas-api-public",
};
