export const META = {
  name: "atlas-api-public",
  description:
    "Versioned public API for registry, search, health, SLOs, and scored assurance evidence",
  version: "1.2.0",
  endpoints: [
    { method: "GET", path: "/v1", description: "Endpoint index" },
    { method: "GET", path: "/v1/docs", description: "Human documentation" },
    { method: "GET", path: "/v1/openapi.json", description: "OpenAPI 3.0 spec" },
    { method: "GET", path: "/v1/registry", description: "Worker registry, stable public shape" },
    { method: "GET", path: "/v1/search", description: "RAG search over the estate corpus (?q=)" },
    { method: "GET", path: "/v1/stats", description: "Estate stats: repos, components, measured uptime" },
    { method: "GET", path: "/v1/slo", description: "Per-day probe counters for error budget maths; window labelled" },
    { method: "GET", path: "/v1/infra/status", description: "Infra health state from specular-sentinel" },
    { method: "GET", path: "/v1/rag/stats", description: "RAG query counts, no query text" },
    { method: "GET", path: "/v1/evidence", description: "Public assurance evidence index" },
    { method: "GET", path: "/v1/evidence/conformance", description: "Latest scored estate conformance report" },
    { method: "GET", path: "/v1/evidence/chaos", description: "Latest chaos assurance report set" },
    { method: "GET", path: "/v1/badge/status", description: "SVG status badge" },
    { method: "POST", path: "/v1/infra/report", description: "Sentinel ingest (bearer)" },
    { method: "POST", path: "/v1/rag/report", description: "Corpus summary ingest (bearer)" },
    { method: "POST", path: "/v1/evidence/{kind}/report", description: "Assurance evidence ingest (bearer)" },
  ],
  source: "https://github.com/AtlasReaper311/atlas-api-public",
};
